package app.gunjan.webservices

class Constants {
    object Partial {
        const val BASE_URL = "http://3.143.37.165:3030/api/"
        const val signup = "auth/signup"
        const val privacyAndPolicy = "auth/privacyAndPolicy"
        const val termAndConditions = "auth/termAndConditions"
        const val verifyOtp = "auth/verifyOtp"
        const val resendOtp = "auth/resendOtp"
        const val login = "auth/login"
        const val completeProfile = "auth/completeProfile"
        const val addAboutYourself = "auth/addAboutYourself"
        const val addIdenificationFile = "auth/addIdenificationFile"
        const val getAllCategoryList = "community/getAllCategoryList"
        const val getAllCommunityList = "community/getAllCommunityList"
        const val addCommunity = "community/addCommunity"
        const val sendCommunityRequest = "auth/sendCommunityRequest"
        const val getUserDetails = "user/getUserDetails"
        const val getAllInterest = "user/getAllInterest"
        const val editProfile = "user/editProfile"
        const val getAllCommunityRequest = "community/getAllCommunityRequest"
        const val acceptRejectRequest = "community/acceptRejectRequest"
        const val getCommunityDetails = "community/getCommunityDetails"
        const val getNotificationList = "notification/get"
    }

    object Keys {
        const val language = "language"
        const val mobile = "mobile"
        const val countryCode = "countryCode"
        const val device_type = "device_type"
        const val code = "code"
        const val profile_name = "profile_name"
        const val first_name = "first_name"
        const val last_name = "last_name"
        const val pincode = "pincode"
        const val image = "image"
        const val token = "token"
        const val about = "about"
        const val identification_file = "identification_file"
        const val title = "title"
        const val category = "category"
        const val page = "page"
        const val limit = "limit"
        const val search = "search"
        const val communityId = "communityId"
        const val email = "email"
        const val dob = "dob"
        const val interests = "interests"
        const val gender = "gender"
        const val type = "type"
        const val request_id = "request_id"
        const val status = "status"
        const val otp_for = "otp_for"
    }
}
